services:

  app:
    build: .
    command: tail -f /dev/null 
    volumes:
      - ./:/workspace:cached

  db:
    image: postgres:12.19
    restart: always          
    environment: 
      POSTGRES_USER: devtedsuser
      POSTGRES_PASSWORD: devtedspass
      POSTGRES_DB: demodb
    volumes:                 
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5050:5432"
    

    # POSTGRES_HOST_AUTH_METHOD: "trust"
    # PGHBA_CONF_CONTENT: |
    #   host    all             all             0.0.0.0/0               md5    
    # - ./pgdata:/var/lib/postgresql/data
      # host    all             all             0.0.0.0/0               trust

volumes:
  pg-data: 5050
